default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nela_development

  #username: nela
  #password:

test:
  <<: *default
  database: nela_test

production:
  <<: *default
  database: nela_production
  username: nela
  password: <%= ENV["NELA_DATABASE_PASSWORD"] %>
